version: '3.5'

services:

   php:
     build:
       context: .
       args:
         user: '1000'
         uid: '1000'
     tty: true
     volumes:
       - ./:/var/www/html
     depends_on:
       - db

   nginx:
     image: nginx:stable-alpine
     tty: true
     ports:
       - "8000:80"
       - "443:443"
     volumes:
       - ./:/var/www/html
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - db
       - php

   db:
     build: ./docker/mysql/.
     container_name: mysql
     tty: true
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     ports:
       - "3306:3306"
     volumes:
       - ./docker/mysql/files:/var/lib/mysql
